### ISSUE TITLE
cannot find module './credentials.js'

### ISSUE THREAD

**Issue by thinksource** [EthanRBrown/web-development-with-node-and-express#12]
I am new for express and node.

After I download the project from git and I try to compile and run it.

```
C:\git\web-development-with-node-and-express>npm install
...
C:\git\web-development-with-node-and-express>node meadowlark.js

module.js:340
    throw err;
    ^
Error: Cannot find module './credentials.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\git\web-development-with-node-and-express\meadowla
rk.js:13:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I do not know what the './credentials.js' for and how to make it can find it?

**Comment by yanlee26** [comment]
fine @EthanRBrown
