### ISSUE TITLE
ch13 - error on cart checkout when when using clustering

### ISSUE THREAD

**Issue by kimko** [EthanRBrown/web-development-with-node-and-express#19]
Hi,
thx for the book and this repository. After checking out ch13 I am facing the following issue:
1) node meadowlark_cluster.js
2) browse to hood-river and add a tour to the cart
3) checkout
4) _error - 404_
(everything works fine when running meadowlark.js directly... the problem seems to be around the clustering(

It looks like the express framework throws an error when rendering the check out 

``` javascript
app.get('/cart/checkout', function(req, res, next) {
    var cart = req.session.cart;
    if (!cart) next();
    res.render('cart-checkout');
});
```

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.set.res.header (/Users/kimkopowski/nodeJs/web-development-with-node-and-express/node_modules/express/lib/response.js:551:10)

help or comment appreciated!

**Comment by qiujumper** [comment]
I'm having this issue as well, not sure what happened, please help us:)
