### ISSUE TITLE
npm zombie install error

### ISSUE THREAD

**Issue by csuarezgfx** [EthanRBrown/web-development-with-node-and-express#23]
installing zombie produces this error.

```
cc@DELL:~/projects/meadowlark/site$ npm install --save-dev zombie
npm WARN package.json meadowlark@1.0.0 No repository field.
npm WARN package.json meadowlark@1.0.0 No README data
 
> contextify@0.1.13 install /home/cc/projects/meadowlark/site/node_modules/zombie/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
 System Linux 3.2.0-4-686-pae
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cc/projects/meadowlark/site/node_modules/zombie/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> utf-8-validate@1.0.1 install /home/cc/projects/meadowlark/site/node_modules/zombie/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cc/projects/meadowlark/site/node_modules/zombie/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.0.1
 
> bufferutil@1.0.1 install /home/cc/projects/meadowlark/site/node_modules/zombie/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Linux 3.2.0-4-686-pae
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cc/projects/meadowlark/site/node_modules/zombie/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.37
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.0.1
npm ERR! contextify@0.1.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.13 install script.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-686-pae
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "zombie"
npm ERR! cwd /home/daniel/projects/meadowlark/site
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

has anybody else experienced this?

**Comment by csuarezgfx** [comment]
SOLVED: ```$ sudo apt-get install build-essential```
then ran ```npm install --save-dev zombie```
