### ISSUE TITLE
Chapter 8 - problem with jquery-file-upload

### ISSUE THREAD

**Issue by J-Miao** [EthanRBrown/web-development-with-node-and-express#26]
When I run the example code of this chapter, after filling the form and uploaded png files, clicking the sumbit button will prompt to submit a file. It seems that the jquery-file-upload plugin has sent the request when uploading files. The form submission and the file upload are not synchronized.

**Comment by jsmasterathul** [comment]
I am also getting the same issue, has anyone looked into it?

**Comment by EthanRBrown** [comment]
It's been a while since I looked at this code, and I'm busy on another book right now; I will try to get to this, but it might not be until September.  If anyone figures it out, I am happy to accept a community PR!

**Comment by oldmannt** [comment]
anyone know how to fix this?

**Comment by xh63hs** [comment]
I am also getting the same issue. Server is crashed. 
the messages are:
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.unlink (fs.js:939:14)
......
Someone said node version is high
My node,js  is  v10.15.0
