### ISSUE TITLE
Chapter 14 - TypeError: Cannot read property 'requiresWaiver' of null

### ISSUE THREAD

**Issue by marcdavies87** [EthanRBrown/web-development-with-node-and-express#59]
From the end of Chapter 14, with the code from github I am seeing the following. 

TypeError: Cannot read property 'requiresWaiver' of null
    at /home/marc/meadowlark/site/lib/cartValidation.js:5:58
    at Array.some (native)
    at Object.module.exports.checkWaivers [as handle] (/home/marc/meadowlark/site/lib/cartValidation.js:5:17)
    at next_layer (/home/marc/meadowlark/site/node_modules/express/lib/router/route.js:103:13)
    at /home/marc/meadowlark/site/handlers/cart.js:30:4
    at _fulfilled (/home/marc/meadowlark/site/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/marc/meadowlark/site/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/marc/meadowlark/site/node_modules/q/q.js:796:13)
    at /home/marc/meadowlark/site/node_modules/q/q.js:604:44
    at runSingle (/home/marc/meadowlark/site/node_modules/q/q.js:137:13)
    at flush (/home/marc/meadowlark/site/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)

I have deleted the node_module directory and reinstalled using npm install.

**Comment by marcdavies87** [comment]
Cleared the session for the cart in the database and this resolved the above.
